name: Deploy Ecommerce App
on:
  push:
    branches:
      - master

jobs:
  push-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - run: docker build -t nhan472569/ecommerce-client ./client
      - run: docker build -t nhan472569/ecommerce-nginx ./nginx
      - run: docker build -t nhan472569/ecommerce-server ./server
      - run: docker push nhan472569/ecommerce-client
      - run: docker push nhan472569/ecommerce-nginx
      - run: docker push nhan472569/ecommerce-server

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: ecommerce-react
          environment_name: Ecommerce-react-env
          existing_bucket_name: elasticbeanstalk-us-east-1-652826177110
          region: us-east-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip
